notifications:
  email: false
dist: xenial
sudo: false
language: c
compiler:
  # Comment out for now to keep build matrix small
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libedit-dev
      - libpng-dev
      - graphviz
env:
  # Configurations
  #
  # Each line in the ``env`` section represents a set of environment
  # variables passed to a build configuration
  #
  # Test a mix of llvm versions, a mix of build systems, and a mix of shared vs static library
  # Don't build as a static library with cmake. It risks exceeding the travis memory limit.
  - LLVM_VERSION=7.0.0 BUILD_SYSTEM=MAKE CXX_=g++-7 CC_=gcc-7 CXX=g++-7 CC=gcc-7
  #CXX_=g++-4.9 CC_=gcc-4.9

cache: apt

# Note the commands below are written assuming Ubuntu 12.04LTS
before_install:
  # set variables necessary for halide
  - source test/scripts/before_install_travis.sh
  # set envirnoment variables specific to this repo
  - export TEST_HALIDE_GEN=true

install:
  # install framework specific to halide
  - test/scripts/install_travis.sh  
  
  # compile coreir
  - git clone -b master https://github.com/rdaly525/coreir.git
  - cd coreir/build && cmake .. && make -j2 && cd ../..

  # compile clockwork
  - git clone https://github.com/dillonhuff/clockwork.git -b aha
  - cd clockwork && ./misc/install_deps_linux.sh
  - make -j2 libcoreir-cgralib.so && make -j2 libclkwrk.so && cd ..

  # compile BufferMapping
  - git clone -b new_config https://github.com/joyliu37/BufferMapping
  - cd BufferMapping/cfunc && make lib -j2 && cd ../..

  # clone RDAI
  - git clone https://github.com/thenextged/rdai.git

  # create Halide compiler
  - make -j2 distrib

before_script:
  # run test cases for hardware codegens
  - export HALIDE_DEBUG_REDIRECT=""
  - make -C apps/hardware_benchmarks/tests testtravis || exit;
  - make -C apps/hardware_benchmarks/apps  testtravis || exit;

script:
  - echo "Finished running tests and apps"

after_script: |
  # See https://github.com/mernst/plume-lib/blob/master/bin/trigger-travis.sh for documentation
  echo "TRAVIS_BRANCH=$TRAVIS_BRANCH TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
  if [[ ($TRAVIS_BRANCH == master) &&
        ($TRAVIS_PULL_REQUEST == false) ]] ; then
    curl -LO --retry 3 https://raw.github.com/mernst/plume-lib/master/bin/trigger-travis.sh
    sh trigger-travis.sh StanfordAHA Applications $TRAVIS_ACCESS_TOKEN
  fi
    
before_deploy:
  - git config --local user.name "jeffsetter"
  - git config --local user.email "setter@stanford.edu"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
  - make -j2 distrib
  - rm distrib/halide.tgz
  - rm distrib/bin/libHalide.so
  - tar -czvf halide_distrib.tgz distrib

deploy:
  provider: releases
  api_key:
    secure: YejtxKjoEnOV0G1Dt6dPbHsrVJNNi2OZ71d9rIfs4B9ker3x0BO1EfLruNZNA1xhV8iAt1sNBzYJocuDqmCSB5j3aqlIfpkRil2HpHfQXbRtNPbwFCbhyBwVbExgXJom9GVip6+flkBMKDl7kXQg36q8f6rN9ldckp8r0SoSKVZN5kyO8NT1AKpjR+fAqzOmES6D3bvabjDWJzaFcP5WFR+ho/ISmcZwr/SpC51NUqtOvIPDlz2OYW/cMvqJrYyoJOtz9nocJuqhi26mN+i3ZMa8EUGl4MFHkiMapV4pLiOaI9OJCmj5xAjiMYUWVHAAyA2yE9jEE5nGl75qll3DQcP3LYxYfcPUlmcuBVTR0Tyx+JQ9qyLfNjGZD3PZK+s5mrN1ja9vzGv3D2Ry0HxZx+sxeoMmIWCDcRPGayhEHwBFKPj8OhCkcwYx/UJFAbnhDSmhgtU4Fq3MQJhGlK/OkP4+sm4WJvSDNdlWnFoU2CPi+mx2ht5DJpj/b55/T0t9t1eZeiAJzroMXeHvMb3/I/ro7BjIpLrfNwhHfYmyX+45RmhoiWGXnwIxy1SBVUSmxNVtdcOmxfGmig2ZR4Nb/l3GCPpyiGwfhiFvKnK2lyFoe9EBpssWbZwiDHSi9QRLK0VmSzrai2BVNE+GPld2thWZLZJEVC3OpEb+MP/ICE0=
  file: halide_distrib.tgz
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    
