notifications:
  email: false
dist: trusty
sudo: false
language: c
compiler:
  # Comment out for now to keep build matrix small
  #- clang
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - libedit-dev
      - libpng-dev
      - graphviz
env:
  # Configurations
  #
  # Each line in the ``env`` section represents a set of environment
  # variables passed to a build configuration
  #
  # Test a mix of llvm versions, a mix of build systems, and a mix of shared vs static library
  # Don't build as a static library with cmake. It risks exceeding the travis memory limit.
  #- LLVM_VERSION=3.6.2 BUILD_SYSTEM=MAKE CXX_=g++-4.8 CC_=gcc-4.8
  #- LLVM_VERSION=3.7.1 BUILD_SYSTEM=MAKE CXX_=g++-4.8 CC_=gcc-4.8
  #- LLVM_VERSION=3.8.1 BUILD_SYSTEM=MAKE CXX_=g++-4.8 CC_=gcc-4.8
  #- LLVM_VERSION=3.7.1 BUILD_SYSTEM=MAKE CXX_=g++-4.8 CC_=gcc-4.8 HALIDE_SHARED_LIBRARY=1
  #- LLVM_VERSION=3.8.1 BUILD_SYSTEM=CMAKE CXX_=g++-4.8 CC_=gcc-4.8 HALIDE_SHARED_LIBRARY=1
  - LLVM_VERSION=3.7.1 BUILD_SYSTEM=MAKE CXX_=g++-4.9 CC_=gcc-4.9

cache: apt

# Note the commands below are written assuming Ubuntu 12.04LTS
before_install:
  # set variables necessary for halide
  - source test/scripts/before_install_travis.sh
  # set envirnoment variables specific to this repo
  - export TEST_HALIDE_GEN=true

install:
  # install framework specific to halide
  - test/scripts/install_travis.sh  
  # compile coreir
  - git clone https://github.com/rdaly525/coreir.git
  - make -C coreir all

script:
  - pwd
  - test/scripts/build_travis.sh
